import type { Card } from '../types'

export const LINUX_CARDS: Card[] = [
  {
    id: 'linux-01',
    track: 'linux',
    tier: 1,
    lesson: 'w01d1',
    front: 'pwd',
    back: 'Prints the full path of your current directory. You are never lost in a terminal as long as you can run it.',
  },
  {
    id: 'linux-02',
    track: 'linux',
    tier: 1,
    lesson: 'w01d2',
    front: 'cp -r source destination',
    back: 'Copies a directory with everything inside it. Without -r, cp copies only single files.',
  },
  {
    id: 'linux-03',
    track: 'linux',
    tier: 1,
    lesson: 'w01d3',
    front: 'tail -f app.log',
    back: 'Keeps printing new lines as the file grows. This is how people follow logs live.',
  },
  {
    id: 'linux-04',
    track: 'linux',
    tier: 1,
    lesson: 'w01d4',
    front: 'which python3',
    back: 'Prints where the command lives on disk. If nothing prints, it is not installed or not on your PATH.',
  },
  {
    id: 'linux-05',
    track: 'linux',
    tier: 1,
    lesson: 'w01d5',
    front: 'What does PATH hold?',
    back: 'A colon-separated list of directories. When you type a command, the shell searches them in order for that program.',
  },
  {
    id: 'linux-06',
    track: 'linux',
    tier: 1,
    lesson: 'w01d5',
    front: 'Absolute path vs relative path',
    back: 'An absolute path starts with / and works from anywhere. A relative path starts from your current directory.',
  },
  {
    id: 'linux-07',
    track: 'linux',
    tier: 1,
    lesson: 'w02d1',
    front: 'chmod +x script.sh',
    back: 'Adds execute permission so the file can be run with ./script.sh.',
  },
  {
    id: 'linux-08',
    track: 'linux',
    tier: 1,
    lesson: 'w02d1',
    front: 'What does chmod 600 secret.txt do?',
    back: 'Gives the owner read and write (4 plus 2) and nobody else anything. Each digit covers owner, group, others.',
  },
  {
    id: 'linux-09',
    track: 'linux',
    tier: 1,
    lesson: 'w02d2',
    front: 'sudo',
    back: 'Runs a single command as root, the administrator account. Only members of the sudo group may use it.',
  },
  {
    id: 'linux-10',
    track: 'linux',
    tier: 1,
    lesson: 'w02d3',
    front: 'find ~/projects -name "*.log"',
    back: 'Lists every .log file under projects. Quote the pattern so the shell does not expand it first.',
  },
  {
    id: 'linux-11',
    track: 'linux',
    tier: 1,
    lesson: 'w02d3',
    front: 'grep -rn "text" dir/',
    back: 'Searches every file under dir recursively for text and prints matching lines with line numbers.',
  },
  {
    id: 'linux-12',
    track: 'linux',
    tier: 1,
    lesson: 'w02d4',
    front: 'command > file vs command >> file',
    back: 'One angle bracket writes the output to the file, replacing its contents. Two append to the end instead.',
  },
  {
    id: 'linux-13',
    track: 'linux',
    tier: 1,
    lesson: 'w02d4',
    front: 'What does a pipe (|) do?',
    back: 'Sends the output of one command into the next command as its input, with no temporary files.',
  },
  {
    id: 'linux-14',
    track: 'linux',
    tier: 1,
    lesson: 'w02d5',
    front: 'sort | uniq -c',
    back: 'Sorts lines, then counts adjacent duplicates. The classic way to tally how often each value appears.',
  },
  {
    id: 'linux-15',
    track: 'linux',
    tier: 1,
    lesson: 'w02d5',
    front: "sed 's/old/new/g' file",
    back: 'Replaces every old with new on each line and prints the result. The file is unchanged unless you pass -i.',
  },
  {
    id: 'linux-16',
    track: 'linux',
    tier: 1,
    lesson: 'w06d1',
    front: 'kill -9 PID',
    back: 'Forces a process to stop. Plain kill asks politely; -9 is for when that is ignored.',
  },
  {
    id: 'linux-17',
    track: 'linux',
    tier: 1,
    lesson: 'w06d2',
    front: 'df -h',
    back: 'Reports disk space per filesystem in human readable units: size, used, available, and percent full.',
  },
  {
    id: 'linux-18',
    track: 'linux',
    tier: 1,
    lesson: 'w06d3',
    front: 'sudo apt update',
    back: 'Refreshes the catalog of available packages. It installs nothing. Run it before apt install.',
  },
  {
    id: 'linux-19',
    track: 'linux',
    tier: 1,
    lesson: 'w06d4',
    front: 'curl -I example.com',
    back: 'Fetches only the HTTP headers, a quick way to check that a server answers.',
  },
  {
    id: 'linux-20',
    track: 'linux',
    tier: 1,
    lesson: 'w06d5',
    front: 'scp report.txt user@host:/tmp/',
    back: 'Copies a file to a remote machine over SSH. The colon marks the remote side.',
  },
  {
    id: 'linux-21',
    track: 'linux',
    tier: 1,
    lesson: 'w11d1',
    front: 'export NAME=value',
    back: 'Makes NAME an environment variable, so programs started from this shell can see it too.',
  },
  {
    id: 'linux-22',
    track: 'linux',
    tier: 1,
    lesson: 'w11d2',
    front: '#!/bin/bash',
    back: 'The shebang, first line of a script. It tells the system which program should run the file.',
  },
  {
    id: 'linux-23',
    track: 'linux',
    tier: 1,
    lesson: 'w11d3',
    front: 'What does exit code 0 mean?',
    back: 'Success. Any other exit code means failure. echo $? shows the code of the last command.',
  },
  {
    id: 'linux-24',
    track: 'linux',
    tier: 1,
    lesson: 'w11d4',
    front: '30 2 * * * /home/learner/backup.sh',
    back: 'A crontab line: run backup.sh at 02:30 every day. The five fields are minute, hour, day, month, weekday.',
  },
  {
    id: 'linux-25',
    track: 'linux',
    tier: 1,
    lesson: 'w11d5',
    front: 'journalctl -u nginx',
    back: 'Shows the full log of the nginx systemd service. Most logs belong to root, so reading them needs sudo.',
  },
]

export default LINUX_CARDS
