import type { Card } from '../types'

export const PYTHON_CARDS: Card[] = [
  {
    id: 'python-01',
    track: 'python',
    tier: 1,
    lesson: 'w03d1',
    front: 'print("Total:", 42)',
    back: 'Prints both values with a space between them. Commas separate the things print shows.',
  },
  {
    id: 'python-02',
    track: 'python',
    tier: 1,
    lesson: 'w03d2',
    front: 'f-string',
    back: 'A string with f before the opening quote. Variables in braces are filled in: f"{name} is {age}".',
  },
  {
    id: 'python-03',
    track: 'python',
    tier: 1,
    lesson: 'w03d2',
    front: 'int("3")',
    back: 'Converts a string to a whole number. str(4) goes the other way. "3" + 4 is an error.',
  },
  {
    id: 'python-04',
    track: 'python',
    tier: 1,
    lesson: 'w03d3',
    front: 's.strip()',
    back: 'Returns a copy of the string with spaces removed from both ends. The original is unchanged.',
  },
  {
    id: 'python-05',
    track: 'python',
    tier: 1,
    lesson: 'w03d4',
    front: 'What does input() return?',
    back: 'Whatever the user typed, always as a string. Convert with int() before doing math.',
  },
  {
    id: 'python-06',
    track: 'python',
    tier: 1,
    lesson: 'w03d5',
    front: 'Which values count as False in a condition?',
    back: '0, an empty string, and an empty list. Everything else counts as True.',
  },
  {
    id: 'python-07',
    track: 'python',
    tier: 1,
    lesson: 'w04d1',
    front: 'fruits.append("kiwi")',
    back: 'Adds an item to the end of the list in place and returns None. Do not assign the result.',
  },
  {
    id: 'python-08',
    track: 'python',
    tier: 1,
    lesson: 'w04d1',
    front: 'sorted(fruits) vs fruits.sort()',
    back: 'sorted returns a new sorted list. sort orders the list in place and returns None.',
  },
  {
    id: 'python-09',
    track: 'python',
    tier: 1,
    lesson: 'w04d2',
    front: 'range(1, 6)',
    back: 'The numbers 1 through 5. The start is included and the stop is not. range(5) gives 0 to 4.',
  },
  {
    id: 'python-10',
    track: 'python',
    tier: 1,
    lesson: 'w04d3',
    front: 'dict.get(key, default)',
    back: 'Returns the value for key, or default when the key is missing, instead of raising KeyError.',
  },
  {
    id: 'python-11',
    track: 'python',
    tier: 1,
    lesson: 'w04d3',
    front: 'for name, age in ages.items():',
    back: 'Loops over a dictionary, giving each key and its value together. keys() and values() give one side only.',
  },
  {
    id: 'python-12',
    track: 'python',
    tier: 1,
    lesson: 'w04d4',
    front: 'What does a function with no return give back?',
    back: 'None. return sends a value to the caller and ends the function.',
  },
  {
    id: 'python-13',
    track: 'python',
    tier: 1,
    lesson: 'w04d5',
    front: 'Tuple',
    back: 'An immutable list, like (3, 4). It cannot be changed after creation. Unpack it with x, y = point.',
  },
  {
    id: 'python-14',
    track: 'python',
    tier: 1,
    lesson: 'w04d5',
    front: '[n for n in nums if n % 2 == 0]',
    back: 'A list comprehension. Builds a list of the even numbers in one line, replacing a three-line loop.',
  },
  {
    id: 'python-15',
    track: 'python',
    tier: 1,
    lesson: 'w07d1',
    front: 'with open("out.txt", "w") as f:',
    back: 'Opens the file for writing, creating or overwriting it, and closes it when the block ends. Mode "a" appends.',
  },
  {
    id: 'python-16',
    track: 'python',
    tier: 1,
    lesson: 'w07d2',
    front: 'except ValueError as e:',
    back: 'Handles a ValueError raised in the try block and keeps the error object as e. Catch specific errors, not bare except.',
  },
  {
    id: 'python-17',
    track: 'python',
    tier: 1,
    lesson: 'w07d3',
    front: 'from collections import Counter',
    back: 'Imports the Counter name directly from the collections module, so you write Counter, not collections.Counter.',
  },
  {
    id: 'python-18',
    track: 'python',
    tier: 1,
    lesson: 'w07d4',
    front: 'python3 -m venv .venv',
    back: 'Creates a virtual environment, a private Python for one project, in a folder called .venv.',
  },
  {
    id: 'python-19',
    track: 'python',
    tier: 1,
    lesson: 'w07d4',
    front: 'pip freeze > requirements.txt',
    back: 'Records the installed packages so someone else can pip install -r requirements.txt and get the same set.',
  },
  {
    id: 'python-20',
    track: 'python',
    tier: 1,
    lesson: 'w07d5',
    front: 'parser.add_argument("--loud", action="store_true")',
    back: 'Defines a flag with argparse. args.loud is True when --loud is passed, otherwise False.',
  },
  {
    id: 'python-21',
    track: 'python',
    tier: 1,
    lesson: 'w09d1',
    front: '__init__',
    back: 'Runs when an object is created and sets up its attributes. self, its first parameter, is the object itself.',
  },
  {
    id: 'python-22',
    track: 'python',
    tier: 1,
    lesson: 'w09d2',
    front: 'json.load(f) vs json.loads(text)',
    back: 'load reads a file into Python objects. loads parses a string. dump and dumps write them back out.',
  },
  {
    id: 'python-23',
    track: 'python',
    tier: 1,
    lesson: 'w09d3',
    front: 'subprocess.run(cmd, capture_output=True, text=True)',
    back: 'Runs a command given as a list of words. The output comes back as a string in result.stdout.',
  },
  {
    id: 'python-24',
    track: 'python',
    tier: 1,
    lesson: 'w09d4',
    front: 'r.json()',
    back: 'Parses the response body into Python objects. Check r.status_code or r.ok before trusting it.',
  },
  {
    id: 'python-25',
    track: 'python',
    tier: 1,
    lesson: 'w09d5',
    front: "line.split('\"')",
    back: 'Splits a log line on double quotes, isolating the quoted request from the fields before and after it.',
  },
]

export default PYTHON_CARDS
