import type { Card } from '../types'

export const SQL_CARDS: Card[] = [
  {
    id: 'sql-01',
    track: 'sql',
    tier: 1,
    lesson: 'w05d1',
    front: 'SELECT * FROM products',
    back: 'Returns every column of every row in the products table. Name columns instead of * to get only those.',
  },
  {
    id: 'sql-02',
    track: 'sql',
    tier: 1,
    lesson: 'w05d2',
    front: 'INTEGER PRIMARY KEY',
    back: 'Marks the column that identifies each row. It fills itself in with the next number when you leave it out.',
  },
  {
    id: 'sql-03',
    track: 'sql',
    tier: 1,
    lesson: 'w05d2',
    front: "INSERT INTO tags (label, color) VALUES ('sale', 'red')",
    back: 'Adds a row. Name the columns, then give values in the same order. Text in single quotes, numbers bare.',
  },
  {
    id: 'sql-04',
    track: 'sql',
    tier: 1,
    lesson: 'w05d3',
    front: 'ORDER BY price DESC',
    back: 'Sorts rows by price from highest to lowest. Without DESC the sort is ascending.',
  },
  {
    id: 'sql-05',
    track: 'sql',
    tier: 1,
    lesson: 'w05d3',
    front: 'Order of clauses in a SELECT',
    back: 'SELECT, FROM, WHERE, ORDER BY, LIMIT. GROUP BY and HAVING later slot in between WHERE and ORDER BY.',
  },
  {
    id: 'sql-06',
    track: 'sql',
    tier: 1,
    lesson: 'w05d4',
    front: 'UPDATE or DELETE without a WHERE',
    back: 'UPDATE changes every row and DELETE empties the table, with no undo. Run a SELECT with the same WHERE first.',
  },
  {
    id: 'sql-07',
    track: 'sql',
    tier: 1,
    lesson: 'w05d5',
    front: "WHERE name LIKE 'A%'",
    back: 'Matches names starting with A. In a pattern, % is any run of characters and _ is exactly one.',
  },
  {
    id: 'sql-08',
    track: 'sql',
    tier: 1,
    lesson: 'w05d5',
    front: 'How do you test for NULL?',
    back: 'IS NULL or IS NOT NULL. Nothing equals NULL, so WHERE city = NULL never matches.',
  },
  {
    id: 'sql-09',
    track: 'sql',
    tier: 1,
    lesson: 'w08d1',
    front: 'COUNT(*) vs COUNT(city)',
    back: 'COUNT(*) counts every row. COUNT(city) counts only rows where city is not NULL. Aggregates ignore NULL.',
  },
  {
    id: 'sql-10',
    track: 'sql',
    tier: 1,
    lesson: 'w08d2',
    front: 'HAVING COUNT(*) >= 3',
    back: 'Filters groups after GROUP BY using an aggregate. WHERE filters rows before grouping and cannot use aggregates.',
  },
  {
    id: 'sql-11',
    track: 'sql',
    tier: 1,
    lesson: 'w08d2',
    front: 'The GROUP BY rule',
    back: 'Every column in the SELECT is either inside an aggregate or listed in GROUP BY. Break it and the result is meaningless.',
  },
  {
    id: 'sql-12',
    track: 'sql',
    tier: 1,
    lesson: 'w08d3',
    front: 'Primary key',
    back: 'A column that uniquely identifies each row, like customers.id. It never changes and no two rows share it.',
  },
  {
    id: 'sql-13',
    track: 'sql',
    tier: 1,
    lesson: 'w08d3',
    front: 'Foreign key',
    back: "A column holding another table's primary key, like orders.customer_id. REFERENCES makes the database enforce it.",
  },
  {
    id: 'sql-14',
    track: 'sql',
    tier: 1,
    lesson: 'w08d4',
    front: 'JOIN customers c ON c.id = o.customer_id',
    back: 'Pairs each order with the customer whose id equals its customer_id. c and o are table aliases.',
  },
  {
    id: 'sql-15',
    track: 'sql',
    tier: 1,
    lesson: 'w08d4',
    front: 'INNER JOIN',
    back: 'Returns only rows with a match on both sides. A customer with no orders does not appear.',
  },
  {
    id: 'sql-16',
    track: 'sql',
    tier: 1,
    lesson: 'w08d5',
    front: 'LEFT JOIN',
    back: 'Keeps every row from the left table even when nothing matches on the right. The missing side comes back as NULL.',
  },
  {
    id: 'sql-17',
    track: 'sql',
    tier: 1,
    lesson: 'w08d5',
    front: 'Find customers who never ordered',
    back: 'LEFT JOIN orders, then WHERE o.id IS NULL. An inner join cannot answer this question.',
  },
  {
    id: 'sql-18',
    track: 'sql',
    tier: 1,
    lesson: 'w10d1',
    front: 'WHERE price > (SELECT AVG(price) FROM products)',
    back: 'A subquery returning one value acts like a number. This finds products priced above the average.',
  },
  {
    id: 'sql-19',
    track: 'sql',
    tier: 1,
    lesson: 'w10d1',
    front: 'Correlated subquery',
    back: 'A subquery in SELECT that refers to the outer row, computing one value per row, such as each customer\'s order count.',
  },
  {
    id: 'sql-20',
    track: 'sql',
    tier: 1,
    lesson: 'w10d2',
    front: 'CREATE INDEX idx_orders_customer ON orders(customer_id)',
    back: 'Builds a sorted lookup on customer_id so the database jumps to matching rows instead of scanning every row.',
  },
  {
    id: 'sql-21',
    track: 'sql',
    tier: 1,
    lesson: 'w10d2',
    front: 'EXPLAIN QUERY PLAN',
    back: 'Shows how SQLite will run a SELECT. SCAN means read everything; SEARCH USING INDEX means it found a shortcut.',
  },
  {
    id: 'sql-22',
    track: 'sql',
    tier: 1,
    lesson: 'w10d3',
    front: 'UNIQUE',
    back: 'A constraint: no two rows may share the value. Right for an email or a coupon code.',
  },
  {
    id: 'sql-23',
    track: 'sql',
    tier: 1,
    lesson: 'w10d3',
    front: 'ALTER TABLE products ADD COLUMN sku TEXT',
    back: 'Adds a column to an existing table. Existing rows get NULL or the DEFAULT.',
  },
  {
    id: 'sql-24',
    track: 'sql',
    tier: 1,
    lesson: 'w10d4',
    front: 'BEGIN, COMMIT, ROLLBACK',
    back: 'BEGIN starts a transaction. COMMIT makes every change since permanent at once. ROLLBACK throws them all away.',
  },
  {
    id: 'sql-25',
    track: 'sql',
    tier: 1,
    lesson: 'w10d5',
    front: 'cur.execute("INSERT INTO items VALUES (?, ?)", (name, price))',
    back: 'Placeholders let sqlite3 escape the values for you, preventing SQL injection and quoting bugs. Never paste values into SQL.',
  },
]

export default SQL_CARDS
