import { Shell } from '../src/shell/shell'

const sh = new Shell()
sh.seed({
  '/home/learner/notes/todo.txt': 'buy milk\nfix bike\nbuy bread\n',
  '/home/learner/notes/old/': '',
  '/home/learner/hello.sh': '#!/bin/bash\necho "Hello, $USER"\n',
  '/home/learner/data.csv': 'name,age\nann,31\nbob,25\nann,31\n',
})
let fails = 0
const t = (cmd: string, expect: string | RegExp) => {
  let out: string
  try { out = sh.run(cmd).output } catch (e) { out = 'THROW ' + (e as Error).message }
  const pass = typeof expect === 'string' ? out === expect : expect.test(out)
  if (!pass) { fails++; console.log(`FAIL ${JSON.stringify(cmd)}\n  got: ${JSON.stringify(out)}\n  want: ${expect}`) }
}
t('pwd', '/home/learner\n')
t('ls', 'data.csv  hello.sh  notes\n')
t('ls -a', '.  ..  .bashrc  .profile  data.csv  hello.sh  notes\n')
t('cd notes && pwd', '/home/learner/notes\n')
t('cd ..; pwd', '/home/learner\n')
t('cat notes/todo.txt | grep buy', 'buy milk\nbuy bread\n')
t('grep -n -i BUY notes/todo.txt', '1:buy milk\n3:buy bread\n')
t('wc -l notes/todo.txt', '3 notes/todo.txt\n')
t('head -n 1 notes/todo.txt', 'buy milk\n')
t('tail -1 notes/todo.txt', 'buy bread\n')
t('mkdir -p a/b/c && touch a/b/c/x.txt && find a -name "*.txt"', 'a/b/c/x.txt\n')
t('cp -r a a2 && ls a2/b/c', 'x.txt\n')
t('mv a2 a3 && ls', 'a  a3  data.csv  hello.sh  notes\n')
t('rm -r a3 && ls', 'a  data.csv  hello.sh  notes\n')
t('echo hi > f.txt; echo there >> f.txt; cat f.txt', 'hi\nthere\n')
t('sort notes/todo.txt | uniq -c | sort -rn | head -1', /1 fix bike|1 buy milk/)
t('cut -d, -f1 data.csv | sort | uniq -c', '      2 ann\n      1 bob\n      1 name\n')
t('echo hello | tr a-z A-Z', 'HELLO\n')
t("sed 's/buy/get/' notes/todo.txt", 'get milk\nfix bike\nget bread\n')
t("sed -n '2p' notes/todo.txt", 'fix bike\n')
t('./hello.sh', /Permission denied/)
t('chmod +x hello.sh && ./hello.sh', 'Hello, learner\n')
t('ls -l hello.sh', /^-rwxr-xr-x 1 learner learner\s+\d+ \w{3} .. \d\d:\d\d hello.sh\n$/)
t('cat /etc/shadow', /Permission denied/)
t('sudo cat /etc/shadow | head -1', /^root:/)
t('whoami; sudo whoami', 'learner\nroot\n')
t('X=5; echo $((X * 2 + 1))', '11\n')
t('for i in 1 2 3; do echo "n=$i"; done', 'n=1\nn=2\nn=3\n')
t('if [ -f hello.sh ]; then echo yes; else echo no; fi', 'yes\n')
t('if [ -f nope ]; then echo yes; else echo no; fi', 'no\n')
t('greet() { echo "hi $1"; }; greet bob', 'hi bob\n')
t('false; echo $?', '1\n')
t('true && echo ok || echo bad', 'ok\n')
t('ls nope', /cannot access/)
t('ls nope; echo $?', /2\n$/)
t('echo $HOME $USER', '/home/learner learner\n')
t('export GREETING=hello; echo $GREETING', 'hello\n')
t('env | grep GREETING', 'GREETING=hello\n')
t('name=$(whoami); echo "I am $name"', 'I am learner\n')
t('echo *.csv', 'data.csv\n')
t('for f in notes/*; do echo $f; done', 'notes/old\nnotes/todo.txt\n')
t('man ls | head -3', /LS\(1\)/)
t('which ls', '/usr/bin/ls\n')
t('ls --help', /list directory contents/)
t('history | tail -1', /history \| tail -1/)
t('nonsense', 'nonsense: command not found\n')
t('ps aux | grep bash', /learner.*-bash/)
t('sleep 100 &', /^\[1\] \d+\n$/)
t('jobs', /sleep 100/)
t('kill 9999', /No such process/)
t('sudo apt install htop && which htop', /Setting up htop[\s\S]*\/usr\/bin\/htop\n$/)
t('apt install tree', /are you root/)
t('df -h | head -2', /Filesystem.*\n\/dev\/vda1/)
t('uname -r', '6.8.0-45-generic\n')
t('ping -c 2 example.com', /2 packets transmitted, 2 received/)
t('curl -I example.com | head -1', 'HTTP/1.1 200 OK\n')
t('ss -tulpn | grep :22', /sshd/)
t('crontab -l', /no crontab for learner/)
t('echo "0 2 * * * /home/learner/backup.sh" > mycron && crontab mycron && crontab -l', '0 2 * * * /home/learner/backup.sh\n')
t('systemctl status nginx', /inactive \(dead\)/)
t('sudo systemctl start nginx && systemctl is-active nginx', 'active\n')
t('curl -s localhost | grep -c nginx', '2\n')
// scripts
sh.vfs.writeFile('/home/learner/count.sh', '#!/bin/bash\ncount=0\nfor f in "$@"; do\n  if [ -f "$f" ]; then\n    count=$((count + 1))\n  fi\ndone\necho "files: $count"\nif [ $count -eq 0 ]; then\n  exit 1\nfi\n', { owner: 'learner' })
t('bash count.sh data.csv hello.sh nope; echo $?', 'files: 2\n0\n')
t('bash count.sh; echo $?', 'files: 0\n1\n')
sh.vfs.writeFile('/home/learner/fn.sh', '#!/bin/bash\nsay() {\n  local msg="$1"\n  echo "say: $msg"\n  return 3\n}\nsay hello\necho "rc=$?"\nwhile [ "$n" != "2" ]; do n=$((n+1)); echo loop $n; done\ncase_x=ok\necho ${case_x}\n', { owner: 'learner' })
t('bash fn.sh', 'say: hello\nrc=3\nloop 1\nloop 2\nok\n')
t('echo "a b" | while read line; do echo "[$line]"; done', '[a b]\n')
t('printf "%s-%d\\n" x 4', 'x-4\n')
t('seq 3 | xargs echo', '1 2 3\n')
t('du -sh notes', /^\d+(\.\d+)?K?\tnotes\n$/)
t('tree notes', /├── old\n└── todo.txt\n\n1 directories, 1 files/)
t('cat > /etc/x', /Permission denied/)
t('echo ok > /etc/x', /Permission denied/)
t('sudo touch /etc/x && ls /etc | grep -c x', /[1-9]/)
t('clear', '')
t('echo "quote \\"inner\\" done"', 'quote "inner" done\n')
t("echo 'single $HOME'", 'single $HOME\n')
t('echo ${#HOME}', '13\n')
t('echo ${MISSING:-default}', 'default\n')
t('grep -r milk notes', 'notes/todo.txt:buy milk\n')
t('grep -c buy notes/todo.txt', '2\n')
t('find . -type d -name old', './notes/old\n')
t('journalctl -u nginx', /No entries/)
// tab completion
const c1 = sh.complete('cat no')
if (c1.replaced !== 'cat notes/') { fails++; console.log('FAIL complete', c1) }
const c2 = sh.complete('ec')
if (c2.replaced !== 'echo ') { fails++; console.log('FAIL complete2', c2) }
const c3 = sh.complete('ls notes/')
if (!c3.options.includes('notes/todo.txt')) { fails++; console.log('FAIL complete3', c3) }
// incomplete
try { sh.run('for i in 1 2; do'); fails++; console.log('FAIL: expected Incomplete') } catch (e) { if ((e as Error).constructor.name !== 'Incomplete') { fails++; console.log('FAIL wrong throw', e) } }
console.log(fails ? `${fails} FAILURES` : 'ALL SHELL SMOKE TESTS PASSED')
process.exit(fails ? 1 : 0)
